name: Trigger auto deployment for rcb

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rcb-AutoDeployTrigger-d7b8ea9a-fbd2-4c8b-9e8b-54f4011dd9c1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RCB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RCB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RCB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}01-Docker/web-app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: bharadwajreddy.azurecr.io
          registryUsername: ${{ secrets.RCB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RCB_REGISTRY_PASSWORD }}
          containerAppName: rcb
          resourceGroup: docker-workshop
          imageToBuild: bharadwajreddy.azurecr.io/rcb:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


