name: Trigger auto deployment for rcb

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rcb-AutoDeployTrigger-7f2f1fd1-f2d2-4452-a9cf-0d2da5819e6c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RCB_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/01-Docker/web-app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: bharadwajreddy.azurecr.io
          registryUsername: ${{ secrets.RCB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RCB_REGISTRY_PASSWORD }}
          containerAppName: rcb
          resourceGroup: docker-workshop
          imageToBuild: bharadwajreddy.azurecr.io/rcb:${{ github.sha }}
          
            

     

